Prevent crimson_tng_find_with_addr from timing out too early
I believe I was able to track down the root cause of

Creating the usrp device with: ...
Error: LookupError: KeyError: No devices found for ----->
Empty Device Address

Waiting only 50 ms (or any negligibly small amount of time) is probably fine after the first response is received. However, there is undoubtedly
some amount of processing time required to simply get the first response. Furthermore, there is also some statistical probability that the message
will be processed and a response sent & received in that amount of time.

Maybe in the future we could gather some statistics about response latency, but for now, I'll just use a bigger magic number. Say 200ms.
The default is 100ms.